**How to use array Function?**

In [ ]:
from numpy import array
l = [1, 2, 3]
a = array(l)
print(a)
print(a.shape)

[1 2 3]
(3,)


**How to use empty Function?**

In [ ]:
from numpy import empty
a = empty([3, 1])
print(a)


[[4.9e-324]
 [9.9e-324]
 [1.5e-323]]


**How to use Zero Function?**

In [ ]:
from numpy import zeros
a = zeros([3,5])
print(a)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


**How to use Ones Function?**

In [ ]:
from numpy import ones
a = ones([5,5])
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**How to remove float number to integer number ?**

In [ ]:
from numpy import array
a = ones([5])
b = a.astype(int)
print(b)

[1.0 1.0 1.0 1.0 1.0]


**How to use vstack Function?**

In [ ]:
from numpy import array
from numpy import vstack
a1 = array([1, 2, 3])
print(a1)
a2 = array([4, 5, 6])
# vstack function to combine array together like vertical line
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

(3,)
[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


**How to use hstack Fucntion? **
hstack combine array together like horizontal

In [ ]:
from numpy import array
from numpy import hstack
a1 = array([1, 2, 3])
a2 = array([4, 5, 6])
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3 4 5 6]
(6,)


** One-Dimensional List to Array**



In [ ]:
from numpy import array
data = ([11, 22, 33, 44, 55])
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


Two-Dimensional List of List to Array

In [ ]:
from numpy import array
data = [[11,22],
    [33, 44],
    [55, 66]],
data = array(data)
print(data)
print(type(data))




[[[11 22]
  [33 44]
  [55 66]]]
<class 'numpy.ndarray'>


One-Dimensional Index

In [ ]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data[0])
print(data[4])

11
55


Reverse Index

In [ ]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data[-1])
print(data[-5])

55
11


In [ ]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data[0])

11


In [ ]:
from numpy import array
data = [[11, 22],
        [33, 44],
        [55, 66]],
data = array(data)
print(data[0,0])

[[[11 22]
  [33 44]
  [55 66]]]
[11 22]


In [ ]:
import numpy as np
data = np.array([
    [11, 22],
    [33, 44],
    [55, 66],
])
print(data[0,0])

[[11 22]
 [33 44]
 [55 66]]
11


In [ ]:
from numpy import array
data = array([
    [11, 22],
    [33, 44],
    [55, 66],
])
print(data[0,])

[11 22]


Array Slicing

In [ ]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data[:])


[11 22 33 44 55]


In [ ]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data[0:1])

[11]


In [ ]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


Two-Dimensional Slicing

In [ ]:

from numpy import array
data = array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99],
])
x = data[ :, :-1]
y = data[:, -1]
print(x)
print(y)


[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


In [ ]:
from numpy import array
data = array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99],
])
split = 3
train, test= data[:split,:], data[split:,:]
print(train,test)

[[11 22 33]
 [44 55 66]
 [77 88 99]] []


Array Rashaping

In [ ]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data)
print(data.shape)

[11 22 33 44 55]
(5,)


In [ ]:
from numpy import array

# 3D array
data_3d = array([
    [[11, 22, 33], [44, 55, 66]],  # First 2D array
    [[77, 88, 99], [111, 122, 133]],
    [[101, 102, 103], [104, 105, 106]]
])
print(data_3d)
print(data_3d.shape)
# How to read 3D in numpy 3 layers 1 layers has 2 row and 2 row has 3 column


[[[ 11  22  33]
  [ 44  55  66]]

 [[ 77  88  99]
  [111 122 133]]

 [[101 102 103]
  [104 105 106]]]
(3, 2, 3)


In [3]:
from numpy import array
data = array([11, 22, 33, 44, 55])
data = data.reshape((data.shape[0], 1))
print(data)
print(data.shape)

[[11]
 [22]
 [33]
 [44]
 [55]]
(5, 1)


In [5]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = 2
print(b)
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


In [8]:
from numpy import array
A = array([
    [1, 2, 3],
    [1, 2, 3],
])
print(A)
B = 2
print(B)
C = A + B
print(C)

[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]
