In [1]:
from numpy import array
from numpy import triu
from numpy import tril
M = array([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3],
])
print(M)
lower = tril(M)
print(lower)
upper = triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


In [7]:
import numpy as np
result = np.arange(5)
h = result.reshape(5,1)
print(h)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [11]:
from numpy import array
from numpy import diag
M  = ([
    [1, 0, 9],
    [1, 9, 3],
    [2, 1, 0]
])
print(M)
d = diag(M)
print(d)

[[1, 0, 9], [1, 9, 3], [2, 1, 0]]
[1 9 0]


In [12]:
# diag function
from numpy import array
from numpy import diag
M = ([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3],
])
print(M)
d = diag(M)
print(d)
D = diag(d)
print(D)

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [20]:
# identity matrix
from numpy import identity
I = identity(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
from numpy import array
from numpy.linalg import inv
Q = array([
    [1, 0],
    [0, -1],
])
print(Q)
V = inv(Q)
print(V)

[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]


In [25]:
import numpy as np
m = np.array([
    [1, 0],
    [0, 3],
])
result = np.linalg.inv(m)
print(result)

[[1.         0.        ]
 [0.         0.33333333]]


In [28]:
import numpy as np
a= np.array([[1, 2], [4, 5], [7, 8]])
print(a)
b=np.transpose(a)
print(b)


[[1 2]
 [4 5]
 [7 8]]
[[1 4 7]
 [2 5 8]]
