In [ ]:
from numpy import array
a = array([[1, 2, 3], [3, 4, 5]])
print(a)

[[1 2 3]
 [3 4 5]]


**Matrix Addicttion**

In [4]:
from numpy import array
a = array([
    [1, 2, 3],
    [4, 5, 6],
])
# print(a)
b = array([
    [6, 7, 8],
    [9, 4, 5],
])
# print(b)
print(a+b)

[[1 2 3]
 [4 5 6]]
[[6 7 8]
 [9 4 5]]
[[ 7  9 11]
 [13  9 11]]


**Matrix Subtraction**

In [5]:
from numpy import array
a = array([
    [1, 2, 3],
    [4, 5, 6],
])
b = array([
    [6, 7, 8],
    [9, 4, 5],
])
print(a-b)

[[-5 -5 -5]
 [-5  1  1]]


In [7]:
from numpy import array
a = array([
    [1, 3, 4],
    [5, 6, 7],
])
b = array([
    [0.5, 0.5, 0.7],
    [0.2, 0.5 , .9]
])
c = a - b
print(c)

[[0.5 2.5 3.3]
 [4.8 5.5 6.1]]


In [9]:
from numpy import array
a = array([
    [1, 2, 3],
    [4, 5, 6],
])
b = array([
    [1, 2, 3],
    [4, 5, 6]
])
c = a*b
print(c)

[[ 1  4  9]
 [16 25 36]]


In [10]:
from numpy import array
a = array([
    [1, 2, 3],
    [4, 5, 6],
])
b = 5
c = a* 5
print(c)

[[ 5 10 15]
 [20 25 30]]


In [15]:
from numpy import array
a = array([
    [1, 2, 3],
    [4, 2, 9]
])
print(a)
b = array([
    [1],
    [2],
    [3],
])
print(b)
print(a *b)

[[1 2 3]
 [4 2 9]]
[[1]
 [2]
 [3]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [14]:
from numpy import array
a = array([
    [1, 2, 3],
    [4, 2, 9]
])
b = ([1, 2,0])
c = a * b
print(c)

[[1 4 0]
 [4 4 0]]


In [19]:
from numpy import array
from numpy import reshape
a = array([
    [1, 2, 3],
    [4, 2, 9]
])
print(a)
b = array([
    [1, 2, 3]
])

print(b)
print(a *b)

[[1 2 3]
 [4 2 9]]
[[1 2 3]]
[[ 1  4  9]
 [ 4  4 27]]


**Matrix  Divison **

In [22]:
from numpy import array
a = array([
    [12, 7, 3],
    [4, 5, 6],
])
b = array([
    [6, 7, 8],
    [9, 4, 5],
])
print(a/b)

[[2.         1.         0.375     ]
 [0.44444444 1.25       1.2       ]]


In [23]:
from numpy import array
a = array([
    [1, 2, 3],
    [4, 5, 6]
])
b = array([1, 2, 3])
print(a/b)

[[1.  1.  1. ]
 [4.  2.5 2. ]]
