In [2]:
from numpy import array
from numpy.linalg import eig
a = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(a)
values, vectors = eig(a)
print(values)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [4]:
from numpy import array
from numpy.linalg import eig
a = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(a)
values, vectors = eig(a)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [5]:
from numpy import array
from numpy.linalg import eig
a = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
values, vectors = eig(a)
b = a.dot(vectors[:, 0])
print(b)
c = vectors[:, 0] * values[0]
print(c)

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


In [9]:
from numpy import array
from numpy.linalg import eig
from numpy.linalg import inv
from numpy import diag
a = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
values, vectors = eig(a)
print(values)
Q = vectors
print(Q)
R = inv(Q)
print(R)
L = diag(values)
print(L)
B = Q.dot(L).dot(R)
print(B)


[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
[[-0.48295226 -0.59340999 -0.70386772]
 [-0.91788599 -0.24901003  0.41986593]
 [ 0.40824829 -0.81649658  0.40824829]]
[[ 1.61168440e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11684397e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.30367773e-15]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
