In [3]:
from numpy import array
from scipy.linalg import lu
a = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
P, L, U = lu(a)
print(P)
print(L)
print(U)
b = P.dot(L).dot(U)
print(b)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [4]:
from numpy import array
from scipy.linalg import qr
a = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
Q, R = qr(a)
print(Q)
print(R)

[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]


In [9]:
from numpy import array
from numpy.linalg import cholesky
a = array([
    [2, 1, 1],
    [1, 2, 1],
    [1, 1, 2]
])
b = a.transpose()
c = a.dot(b)
L = cholesky(a)

print(a)
print(b)
print(c)
print(L)



[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[6 5 5]
 [5 6 5]
 [5 5 6]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]


In [15]:
from numpy import array
from numpy.linalg import cholesky
from scipy.linalg import lu
a = array([
    [2, 1, 1],
    [1, 2, 1],
    [1, 1, 2]
])
L, U, _  = lu(a)
L_tran = L.transpose()
result = L.dot(L_tran)
print(a)
print(L)
print(result)



[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
