In [ ]:
from numpy import array
from scipy.sparse import csr_matrix
a = array([
    [1, 2, 3],
    [4, 5, 6]
])
b = csr_matrix(a)
print(b)

  (0, 0)	1
  (0, 1)	2
  (0, 2)	3
  (1, 0)	4
  (1, 1)	5
  (1, 2)	6


In [ ]:
from numpy import array
from scipy.linalg import svd
a = array([
    [1, 2],
    [3, 4],
    [5, 6]
])
u, s, v = svd(a)
print(u)
print(s)
print(v)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [1]:
from numpy import array
from scipy.linalg import svd
a = array([
    [1, 2],
    [3, 4],
    [5, 6]
])
U, s, V = svd(a)
print(U)
print(s)
print(V)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [2]:
from numpy import array
from numpy import diag
from scipy.linalg import svd
a = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(a)
u, s, v = svd(a)
sigma = diag(s)
b = u.dot(sigma.dot(v))
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
