In [ ]:
from numpy import array
from scipy.sparce import csr_matrix
a = array([
    [1, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 1],
    [0, 0, 0, 2, 0, 0]
])
print(a.shape)

(3, 6)


In [ ]:
# Import necessary functions from scipy.sparse
from scipy.sparse import csr_matrix
import numpy as np


dense_matrix = np.array([
    [1, 0, 1],
    [1, 0, 0],
    [0, 3, 0]
])


sparse_matrix = csr_matrix(dense_matrix)


print(sparse_matrix)


print(sparse_matrix.toarray())


  (0, 0)	1
  (0, 2)	1
  (1, 0)	1
  (2, 1)	3
[[1 0 1]
 [1 0 0]
 [0 3 0]]


In [ ]:
from numpy import array
from numpy import triu
a = array([
    [1, 2, 3],
    [3, 4, 5],
    [7, 8, 9]
])
print(a)
result = triu(a,1)
print(result)


[[1 2 3]
 [3 4 5]
 [7 8 9]]
[[0 2 3]
 [0 0 5]
 [0 0 0]]


In [ ]:
from numpy import array
from numpy import tril
a = array([
    [1, 2, 3],
    [3, 4, 5],
    [7, 8, 9]
])
print(a)
result = tril(a,-1)
print(result)

[[1 2 3]
 [3 4 5]
 [7 8 9]]
[[0 0 0]
 [3 0 0]
 [7 8 0]]


In [4]:
from numpy import array
from scipy.sparse import csr_matrix
a = array([
    [1, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 1],
    [0, 0, 0, 2, 0, 0],
])
print(a)
s = csr_matrix(a)
print(s)
b = s.todense()
print(b)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [6]:
from numpy import array
from numpy import count_nonzero
a = array([
    [1, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 1],
    [0, 0, 0, 2, 0, 0],
])
print(a)
sp = count_nonzero(a)
print(sp)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
5
