In [1]:
from numpy import array
a = array([1, 2, 3])
b = array([1, 2, 3])
c = a + b
print(c)

[2 4 6]


**Scalar and one-Dimensional Array**

In [3]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = 2
print(b)
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


In [6]:
from numpy import array
a = array([
    [1, 2, 3],
    [1, 2, 3],
])
print(a)
b = 2
print(b)
c = a + b
print(c)

[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]


In [9]:
from numpy import array
a = array([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]])
print(a)
b = 3
print(b)
c = a + b
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
[[[ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


Ones-Dimensional and Two-Dimensional Array

In [13]:
from numpy import array
a = array([
    [1, 2, 3],
    [1, 2, 3],
])
print(a)
b = array([4, 1, 2])
print(b)
c = a + b
print(c)

[[1 2 3]
 [1 2 3]]
[4 1 2]
[[5 3 5]
 [5 3 5]]


In [17]:
print(a.shape)
print(b.shape)


(2, 3)
(3,)
