**How to define a Vector?**

In [ ]:
from numpy import array
v = array([1, 2, 3])
print(v)

[1 2 3]



How to added Vector together?


In [ ]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([4, 5, 6])
print(b)
c = a + b
print(c)

[1 2 3]
[4 5 6]
[5 7 9]


**How to use Vector Subtraction?**

In [ ]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([0.5, 0.3, 4])
b = b.astype(int)
c = a - b
print(c)

[1 2 3]
[ 1  2 -1]


**How to use Vector Multiplication?**

In [ ]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


**How to use Vector Division?**

In [ ]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a / b
print(c)

[1 2 3]
[1 2 3]
[0 0 0]


How to use Dot?

In [ ]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([4, 5, 6])
print(b)
c = a.dot(b)
print(c)

[1 2 3]
[4 5 6]
32


In [ ]:
import numpy as np
a = ([1, 2, 3])
print(a)
b = ([4, 5, 6])
print(b)
c = np.dot(a, b)
print(c)

[1, 2, 3]
[4, 5, 6]
32


In [3]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([7, 2, 1])
print(b)
a = a.dot(b)
print(a)



[1 2 3]
[7 2 1]
14


**How to use Vector scalar multiplication?**

In [4]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = 0.5
print(b)
c = a * b
print(c)

[1 2 3]
0.5
[0.5 1.  1.5]


How to use Vector norm?

In [7]:
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
l1 = norm(a,1)
print(l1)

[1 2 3]
3.3019272488946263
